### ISSUE TITLE
Prevent project received emails going out for endaoment projects to project owner

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/notification-center#100]
Since Endaoment projects will be owned by one profile, it does not make sense for donations received to trigger an email sent to the project owner. we should disable this by default. 

## AC

- [x] When making a donation to an endaoment project there is no email received to the project owner.

**Comment by divine-comedian** [comment]
@maryjaf  can you test this one since you are the project owner

**Comment by maryjaf** [comment]
> * When making a donation to an endaoment project there is no email received to the project owner.

Only for donation? or for example for changing status from admin also the email shouldn't be sent

**Comment by divine-comedian** [comment]
> > * When making a donation to an endaoment project there is no email received to the project owner.
> 
> Only for donation? or for example for changing status from admin also the email shouldn't be sent

Only for donation - we should not be needing to change the status of the project from endaoment

**Comment by divine-comedian** [comment]
@maryjaf did this test pass then?

**Comment by maryjaf** [comment]
Yeah, The test  passed
I had donated to an endowment project and the project owner didn't receive any notification.

**Comment by divine-comedian** [comment]
@mohammadranjbarz if you can confirm this requirement is already active on production we can close this issue.

**Comment by divine-comedian** [comment]
@maryjaf did we get a chance to test this?

**Comment by maryjaf** [comment]
> @maryjaf did we get a chance to test this?

No, actually I tested this issue only on staging

**Comment by divine-comedian** [comment]
@maryjaf to provide mitch address so he can send test funds optimism to make donation on production

**Comment by maryjaf** [comment]
> We can test this issue on prod by this method
> 
> 1. change project owner to tester address
> 2. donate to project
> 3. check if donation received email is sent
> 4. if no email is sent test passes
> 5. change project owner back to endaoment.eth
> 
> @mohammadranjbarz @maryjaf can test this together on PRODUCTION

could you please change the project owner for one of the endaoment projects @mohammadranjbarz 
0xcd192b61a8Dd586A97592555c1f5709e032F2505

**Comment by maryjaf** [comment]
> @maryjaf to provide mitch address so he can send test funds optimism to make donation on production
Thanks @divine-comedian 
0xA1179f64638adb613DDAAc32D918EB6BEB824104

**Comment by maryjaf** [comment]
- The ownership of this project is changed to my address https://giveth.io/project/CARE-PERU
- I've donated to this project and the project owner hasn't receive any notification and email related to this donation
