### ISSUE TITLE
Deploy project on production server

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/notification-center#18]
- [x] Create a new postgres DB connection in digital ocean for that
- [x] Setup Github Actions CI/CD
- [x] Setup nginx  ( https://staging.notification.giveth.io goes to staging , I think https://notification.giveth.io id good one for production)
- [x] Restrict /v1/thirdParty/notifications to just can be called from our production server and with our openpn ip
- [x] Fill .env.production with needed data

You can see the staging .env, ci/cd config to see what get more insight, at the end the project should be up in https://notification.giveth.io/docs

Staging swagger: https://staging.notification.giveth.io/docs

**Comment by mhmdksh** [comment]
All the above have now been configured, and notification-center is now up and running on production environment here: https://notification.giveth.io/
