### ISSUE TITLE
Some notification is'not sent  to those who liked the project 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/notification-center#22]
This scenario needs to be checked
-We have notifications that are sent to the project owner, but not to those who liked the project (from both the list page and edit page)

- Listed project
- Activate project
- Verify/Unverify

**Comment by mohammadranjbarz** [comment]
This is the googlesheet that we implemented notifications based on that

- [ ] **Activate project**
I have fixed that, you can test it again 
<img width="992" alt="Screen Shot 1401-10-04 at 14 49 01" src="https://user-images.githubusercontent.com/9850545/209465962-661be513-d40c-4920-9fd1-6d987b65671c.png">


- [ ] **Verify**
I have fixed that, you can test it again 
<img width="1152" alt="Screen Shot 1401-10-04 at 14 48 57" src="https://user-images.githubusercontent.com/9850545/209465965-130bbb1b-2a4b-4a79-8d58-8301399255d2.png">


* **Unverify**
@MoeNick  @maryjaf 
In googlesheet it was noted to just send notification to users who boosted and project owners, if we have to do something else please let me know

<img width="1883" alt="Screen Shot 1401-10-04 at 13 32 55" src="https://user-images.githubusercontent.com/9850545/209463837-60741ffd-744d-4b82-9868-5aa6e9a039aa.png">


* **Listed project**
 @MoeNick  @maryjaf 
 If we need to send more notifications in this case, please let me know
In this case we supposed to send notification just for project manager
<img width="1874" alt="Screen Shot 1401-10-04 at 12 49 45" src="https://user-images.githubusercontent.com/9850545/209462743-ed083d94-5276-49ca-9a49-859fb5bec61e.png">

**Comment by maryjaf** [comment]
> This is the googlesheet that we implemented notifications based on that
> 
> * [x]  **Activate project**
>   I have fixed that, you can test it again
> 
> <img alt="Screen Shot 1401-10-04 at 14 49 01" width="992" src="https://user-images.githubusercontent.com/9850545/209465962-661be513-d40c-4920-9fd1-6d987b65671c.png">
> 
> * [x]  **Verify**
>   I have fixed that, you can test it again
> 
> <img alt="Screen Shot 1401-10-04 at 14 48 57" width="1152" src="https://user-images.githubusercontent.com/9850545/209465965-130bbb1b-2a4b-4a79-8d58-8301399255d2.png">
> 
> * **Unverify**
>   @MoeNick  @maryjaf
>   In googlesheet it was noted to just send notification to users who boosted and project owners, if we have to do something else please let me know
> 
> <img alt="Screen Shot 1401-10-04 at 13 32 55" width="1883" src="https://user-images.githubusercontent.com/9850545/209463837-60741ffd-744d-4b82-9868-5aa6e9a039aa.png">
> 
> * **Listed project**
>   @MoeNick  @maryjaf
>   If we need to send more notifications in this case, please let me know
>   In this case we supposed to send notification just for project manager
> 
> <img alt="Screen Shot 1401-10-04 at 12 49 45" width="1874" src="https://user-images.githubusercontent.com/9850545/209462743-ed083d94-5276-49ca-9a49-859fb5bec61e.png">

Thanks @mohammadranjbarz this problem has been fixed for activate and verify action
