### ISSUE TITLE
Notification Center - Copy Fixes & Some extra Changes....

### ISSUE THREAD

**Issue by laurenluz** [Giveth/notification-center#29]
Ok, I have many copy suggestions for [this page](https://notification-center-13.vercel.app/notifications/settings). I hope they are clear. I also added a few questions/change requests here. Lmk if anything doesn't make sense.

- [x] Change your settings at any time to adjust how and when you see notifications. Important notifications outside of your settings may still be sent to you.
![image](https://user-images.githubusercontent.com/75490971/211385944-24c42613-aa15-43ac-8e30-6c5a4f1b56b8.png)

- [x] "My Project Activity" "Notifications for project owners about project activity." ** need to confirm with @MoeNick & @mosaeedi that this design change is ok.
![image](https://user-images.githubusercontent.com/75490971/211387467-792662d6-d4f3-48b3-bc6b-b80fcd7e50c5.png)

- [x] "Send me an email" "Notify me in the DApp"
![image](https://user-images.githubusercontent.com/75490971/211386632-a382327e-6460-4845-8f2f-e7bda3d6381b.png)

- [x] "Project published" "Notify me when my project has been published."
![image](https://user-images.githubusercontent.com/75490971/211386937-05aa8e03-b50b-4f7d-b846-276468d7eaba.png)

- [x] "Project updated" "Notify me when my project has been edited, or an update has been published."
![image](https://user-images.githubusercontent.com/75490971/211388078-d0ba0690-1adf-4c24-b8a1-7a20888e6e7a.png)

- [x] "Project liked" "Notify me when someone likes my project."
![image](https://user-images.githubusercontent.com/75490971/211388164-f87a5ada-70d8-4260-a36b-5d27445a8b0d.png)

- [x] "Project boosted" "Notify me when a new address boosts my project with GIVpower." @mohammadranjbarz - can you confirm that this notification occurs only for new addresses?
![image](https://user-images.githubusercontent.com/75490971/211388769-f30b5125-671c-4fe0-9391-62113f82d01e.png)

- [x] "Project status" "Notify me when a project I own has been listed, unlisted, cancelled, activated or deactivated."
![image](https://user-images.githubusercontent.com/75490971/211388981-7e2f9369-5655-4ce7-962f-bad558991ab6.png)

- [x] "Donation received" "Notify me when my project receives a donation."
![image](https://user-images.githubusercontent.com/75490971/211389441-217e0c7d-cc5f-4808-9a0c-448135f4ca48.png)

- [x] #30
![image](https://user-images.githubusercontent.com/75490971/211389539-f5807f8c-520f-4112-a970-c7bf195b3eef.png)

- [x] "Supported project updated" "Notify me when a project I liked, boosted or donated to has an update." @MoeNick @mohammadranjbarz - can we confirm that we will make this change?
![image](https://user-images.githubusercontent.com/75490971/211388251-388a01da-ca38-4b92-9d3a-973868f4b093.png)

- [x] "Donations" "Notify me when my donation to a project succeeds or fails."
![image](https://user-images.githubusercontent.com/75490971/211389954-970f9bf4-8f96-4fab-8433-5c4653e3001a.png)

- [x] "Rewards" "Notifications related to GIV rewards and staking."
![image](https://user-images.githubusercontent.com/75490971/211390233-29bb63e5-e03c-41e0-b414-edc32e222005.png)

- [x] "GIVbacks" "Notify me when my GIV from GIVbacks is ready to claim."
![image](https://user-images.githubusercontent.com/75490971/211390575-2bb11941-c968-47cc-ab5b-c3a4390c3116.png)

- [x] #31
![image](https://user-images.githubusercontent.com/75490971/211390712-a0a93f00-38ac-4bcc-a3f6-e357bda9499d.png)

- [x] _Can we delete this one? I thought we decided not to do it_
![image](https://user-images.githubusercontent.com/75490971/211390886-fac0912e-1d10-4443-bd3c-5c8ff739c406.png)

cc @maryjaf @MohammadPCh

**Comment by laurenluz** [comment]
- [ ] Your history of notifications, starting with the most recent.
![image](https://user-images.githubusercontent.com/75490971/211392429-74b8af3d-03af-472b-ba2e-7eaa5b48cb23.png)

**Comment by MohammadPCh** [comment]
@alireza-sharifpour can you take it?

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour can you take it?

Sure, I'll take it

**Comment by laurenluz** [comment]
I think @MoeNick wanted to do a bit of review on this @alireza-sharifpour ...

so if there are some suggestions that I made w/ a comment to @MoeNick, skip those until he gives the thumbs up

**Comment by MoeNick** [comment]
You can start te copy fixes @alireza-sharifpour 
There are some design changes that you can see on the Figma, jfyi on tabs and on setting page we added supported projects notification.

**Comment by alireza-sharifpour** [comment]
@MoeNick We are getting settings copies from the backend, so i think there would be some changes in the backend side.
@mohammadranjbarz @CarlosQ96

**Comment by MoeNick** [comment]
I think we have to include it in related backend issue.

**Comment by MoeNick** [comment]
I assigned it to @mohammadranjbarz cause most of them need db changes

**Comment by mohammadranjbarz** [comment]
@laurenluz 

About below question that you asked, yes we just send one notification per user-project to projectOwner, when someone likes/boosts a project

<img width="752" alt="Screen Shot 1401-11-05 at 11 01 40" src="https://user-images.githubusercontent.com/9850545/214505138-0e14b360-3bc3-49f9-b94d-0cb4f3e077b6.png">

**Comment by mohammadranjbarz** [comment]
@maryjaf @MoeNick  This issue has been implemented and merged 
you can test it here

https://notification-center-13.vercel.app/notifications/settings

**Comment by maryjaf** [comment]
> * Your history of notifications, starting with the most recent.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/111529185/214599714-fd2bb37f-7940-4887-a272-c8f67c2b1e11.png">
In this section the old message is shown

**Comment by maryjaf** [comment]
> * Important notifications outside of your settings may still be sent to you.

and this:
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/111529185/214601331-38a786b4-3708-4bec-a12c-e2be111016ec.png">

**Comment by maryjaf** [comment]
> * "Send me an email" "Notify me in the DApp"

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/111529185/214602787-782dafcc-4389-4c25-888e-323c47ec8fe7.png">

**Comment by maryjaf** [comment]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/111529185/214605420-4a5e4a24-a38a-455a-b2b2-20e4439081b3.png">

"Supported project updated" is duplicated

**Comment by maryjaf** [comment]
> * Notify me only when GIV I staked for GIVpower gets unlocked. #31

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/111529185/214609232-79c5a911-8186-4066-a623-169cb0c3d8c4.png">

**Comment by mohammadranjbarz** [comment]
>  Your history of notifications, starting with the most recent.
> 
> <img alt="image" width="1302" src="https://user-images.githubusercontent.com/111529185/214599714-fd2bb37f-7940-4887-a272-c8f67c2b1e11.png">
> 
> In this section the old message is shown

@maryjaf  @MohammadPCh @alireza-sharifpour  It's related to frontend

**Comment by mohammadranjbarz** [comment]
>  Important notifications outside of your settings may still be sent to you.
> 
> and this: <img alt="image" width="1309" src="https://user-images.githubusercontent.com/111529185/214601331-38a786b4-3708-4bec-a12c-e2be111016ec.png">

@maryjaf  @MohammadPCh @alireza-sharifpour  It's related to frontend

**Comment by mohammadranjbarz** [comment]
>  "Send me an email" "Notify me in the DApp"
> 
> <img alt="image" width="1182" src="https://user-images.githubusercontent.com/111529185/214602787-782dafcc-4389-4c25-888e-323c47ec8fe7.png">

@maryjaf  @MohammadPCh @alireza-sharifpour  It's related to frontend

**Comment by mohammadranjbarz** [comment]
> <img alt="image" width="1125" src="https://user-images.githubusercontent.com/111529185/214605420-4a5e4a24-a38a-455a-b2b2-20e4439081b3.png">
> 
> "Supported project updated" is duplicated

Thanks for finding this, I deleted the repetitive one

**Comment by maryjaf** [comment]
> > * Notify me only when GIV I staked for GIVpower gets unlocked. [Notify me only when GIV I staked for GIVpower gets unlocked. #31](https://github.com/Giveth/notification-center/issues/31)
> 
> <img alt="image" width="1129" src="https://user-images.githubusercontent.com/111529185/214609232-79c5a911-8186-4066-a623-169cb0c3d8c4.png">

Is this related to frontend or backend? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> > > * Notify me only when GIV I staked for GIVpower gets unlocked. [Notify me only when GIV I staked for GIVpower gets unlocked. #31](https://github.com/Giveth/notification-center/issues/31)
> > 
> > 
> > <img alt="image" width="1129" src="https://user-images.githubusercontent.com/111529185/214609232-79c5a911-8186-4066-a623-169cb0c3d8c4.png">
> 
> Is this related to frontend or backend? @mohammadranjbarz

No it's related to backend, thanks for mentioning that, I had forgotten about it, I added this comment

https://github.com/Giveth/notification-center/issues/31#issuecomment-1411604486

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour copy related to frontend has been edited
