### ISSUE TITLE
Notification Center - Notifcations on status change of projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/notification-center#34]
@MoeNick - as per your request, here is some copy/flow for various project status changes. Can you please review them and then assign them to the correct person to implement?

- [x] Project becomes listed --> "Congrats! < project name > is now listed on the Giveth projects page."
- [x] Project becomes unlisted --> "< project name > did not meet our [guidelines for listed projects](https://docs.giveth.io/dapps/listedUnlisted/#listed-projects) and has been hidden from the projects page. You can still share your project directly via the project URL."
- [x] Project gets verified --> "Congrats! < project name > is now verified. Your community can now take advantage of [GIVbacks](https://docs.giveth.io/giveconomy/givbacks) and [GIVpower](https://docs.giveth.io/giveconomy/givpower/)."
- [x] Project *loses* verified status --> " < project name > has lost its verification status. Learn more about our verification requirements [here](https://docs.giveth.io/dapps/projectVerification)."
- [x] Project fails verification --> "< project name > has not been approved for verification. Learn more about our verification requirements [here](https://docs.giveth.io/dapps/projectVerification)."

@MoeNick - I need your confirmation on these ones because I'm not 100% certain I am correct here:

- [x] Project canceled --> "< project name > has been canceled by an admin because it failed to adhere to our [terms of use](https://giveth.io/tos)."
- [x] Project deactivated -->  "You have deactivated your project < project name >."

- Project deleted --> Since this is only possible in the backend, I don't think we need to notify the user about it.

**Comment by MoeNick** [comment]
Thanks @laurenluz 
Actually I meant copies for supported projects for above events

**Comment by laurenluz** [comment]
like notifcations to sent to people who "supported" projects when the project they supported has a status change? @MoeNick

**Comment by MoeNick** [comment]
yes

- status change
- ost verified badge or get verified
- updates

**Comment by laurenluz** [comment]
Notifications to "supported" when the project they supported has a status update, or provides an update:

- [ ] Project becomes listed --> "< project name >, which you supported, is now listed on the Giveth projects page."
- [ ] Project becomes unlisted --> "< project name >, which you supported, did not meet our [guidelines for listed projects](https://docs.giveth.io/dapps/listedUnlisted/#listed-projects) and has been hidden from the projects page.
- [ ] Project gets verified --> "Amazing! < project name >, which you supported, is now verified. You can now donate and receive [GIVbacks](https://docs.giveth.io/giveconomy/givbacks) and or boost it with [GIVpower](https://docs.giveth.io/giveconomy/givpower/)."
- [ ] Project *loses* verified status --> " < project name >, which you supported, has lost its verification status. Learn more about our verification requirements [here](https://docs.giveth.io/dapps/projectVerification)."
- [ ] Project canceled --> "< project name >, which you supported, has been canceled by an admin because it failed to adhere to our [terms of use](https://giveth.io/tos)."
- [ ] Project deactivated -->  "< project name >, which you supported, has been deactivated by the project owner."
- [ ] Project activated --> "< project name >, which you supported, has been reactivated by the project owner."
- [ ] Project provided an update --> "< project name>, which you supported, has a new update!"

For settings page (I think it is ok as it is):
![image](https://user-images.githubusercontent.com/75490971/216060193-0d041df3-b2cd-4b97-bba2-7ca192718d93.png)


@MoeNick - is this good now?

**Comment by MoeNick** [comment]
Shall I move it to done or I have to ask @alireza-sharifpour to do something to get ready to test?

**Comment by mohammadranjbarz** [comment]
> Shall I move it to done or I have to ask @alireza-sharifpour to do something to get ready to test?

I think it's better to wait for frontend guys and after that we can tell @maryjaf to test all these items

**Comment by alireza-sharifpour** [comment]
> Shall I move it to done or I have to ask @alireza-sharifpour to do something to get ready to test?

I'm currently working on PFP collection, after that i'll do work on it.

**Comment by maryjaf** [comment]
> * 
> * [x]  Project deactivated -->  "< project name >, which you supported, has been deactivated by the project owner."
> * [x]  Project activated --> "< project name >, which you supported, has been reactivated by the project owner."

It is possible to deactivate and activate the project by both the project owner and the admin user
Should the same message be displayed in both modes? @MoeNick @laurenluz

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/50ea9a65-3264-4297-b12a-dbe878145675)
This message needs to be corrected (Unlisted status for. project owner)

**Comment by mohammadranjbarz** [comment]
> ![image.png](https://camo.githubusercontent.com/88f64aba2925d10adc006f3d90e03e144a8815ecc1a76a49d1a30248b2b4454a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f35306561396136352d333236342d343239372d623132612d646265383738313435363735) This message needs to be corrected (Unlisted status for. project owner)
@maryjaf  Thank you I fixed it
<img width="1313" alt="Screen Shot 1401-11-23 at 11 40 13" src="https://user-images.githubusercontent.com/9850545/218300066-d5fa11a5-6c23-4b10-8652-4a01f3586192.png">

**Comment by MoeNick** [comment]
> > * [x]   Project deactivated -->  "< project name >, which you supported, has been deactivated by the project owner."
> > * [x]   Project activated --> "< project name >, which you supported, has been reactivated by the project owner."
> 
> It is possible to deactivate and activate the project by both the project owner and the admin user Should the same message be displayed in both modes? @MoeNick @laurenluz

Yes let's remove "by .... "
*[ ]   Project deactivated -->  "< project name >, which you supported, has been deactivated."
*[ ]   Project activated --> "< project name >, which you supported, has been reactivated .
@mohammadranjbarz 
؛ث

**Comment by mohammadranjbarz** [comment]
> > > * [x]    Project deactivated -->  "< project name >, which you supported, has been deactivated by the project owner."
> > > * [x]    Project activated --> "< project name >, which you supported, has been reactivated by the project owner."
> > 
> > 
> > It is possible to deactivate and activate the project by both the project owner and the admin user Should the same message be displayed in both modes? @MoeNick @laurenluz
> 
> Yes let's remove "by .... " *[ ] Project deactivated --> "< project name >, which you supported, has been deactivated." *[ ] Project activated --> "< project name >, which you supported, has been reactivated . @mohammadranjbarz ؛ث

@maryjaf  @MoeNick 
Done

**Comment by maryjaf** [comment]
In some sentences, there is no end point, plz change this @mohammadranjbarz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3edeee15-ac36-4d91-83c7-18617b24b172)

**Comment by maryjaf** [comment]
> * Project deactivated -->  "You have deactivated your project < project name >."

I think since it is currently possible to disable project  both by admin and  by project owner, it would be better to change this sentence. @MoeNick @laurenluz

**Comment by maryjaf** [comment]
> * [x]  Project becomes listed --> "< project name >, which you supported, is now listed on the Giveth projects page."
> * [x]  Project becomes unlisted --> "< project name >, which you supported, did not meet our [guidelines for listed projects](https://docs.giveth.io/dapps/listedUnlisted/#listed-projects) and has been hidden from the projects page.

plz check this @mohammadranjbarz 
I don't receive a notification when the project I liked is listed or unlisted

**Comment by mohammadranjbarz** [comment]
> In some sentences, there is no end point, plz change this @mohammadranjbarz ![image.png](https://camo.githubusercontent.com/693e82f207aac1aaf0e1213a61fbb87534d386a5003f2d9571fd2c7b0fde5420/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f33656465656531352d616333362d346439312d383363372d313836313762323462313732)

@maryjaf Done.
