### ISSUE TITLE
Notify project owner when his project has been edited and the status changed from listed/notlisted to Not Reviewed

### ISSUE THREAD

**Issue by maryjaf** [Giveth/notification-center#40]
This notification is now sent when a project is edited:

Your Project [test101000](https://staging.giveth.io/project/test101000) has been edited
It is better to inform the project owner in this message that the status of the project has changed to Not Reviewed
@MoeNick

**Comment by mohammadranjbarz** [comment]
> This notification is now sent when a project is edited:
> 
> Your Project [test101000](https://staging.giveth.io/project/test101000) has been edited It is better to inform the project owner in this message that the status of the project has changed to Not Reviewed @MoeNick

@MoeNick 
Can you tell me what should I do exactly for this?

**Comment by MoeNick** [comment]
You edited your project {project name} and our team is reviewed it, you'll get notified until your project get listed again.

**Comment by mohammadranjbarz** [comment]
@MoeNick Told me in DM
> You edited your project {project name} and our team is reviewing  it, you'll get notified when it will be listed again.

**Comment by mohammadranjbarz** [comment]
@maryjaf 
You can test it now

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/446aa97e-f1e6-438e-9b8f-fe78655655c2)
Thanks @mohammadranjbarz It is OK now
