### ISSUE TITLE
Notification settings and default value doesnt work properly

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/notification-center#46]
Reported by @maryjaf and @MoeNick 

These notification types should have `email` **OFF** and checkbox should not be editable
- [x] GIVbacks 
- [x] GIVpower Allocation 
- [x] Supported project update
- [x] Supported projects status
- [x] Project Booste status
- [x] Your project update
- [x] Projects likes

**Comment by mohammadranjbarz** [comment]
@maryjaf  @MoeNick It's on staging now

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz I checked and it's ok now
