### ISSUE TITLE
SuperFluid Notifications for Notification Center

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/notification-center#62]
We will have these notifications on the Notification Center:

![Notification Center](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/a91a4e2b-707d-4154-b594-0b0804829cf1)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23293-17833&mode=design&t=V0ZWCYffPNSTpoI7-0

All of these will be fit under the "Project" category in the notification center drop down

# EDIT 05/02/2024 - I removed many of the notifications given the challenges of notification center resource consumption

### On 1 month left in stream balance 
> "Your Stream Balance of {underlyingTokenSymbol} on {network} will run out in 1 month, [top-up here]()."

Link to my recurring donations tab

### On 1 week left in stream balance 
> "Your Stream Balance of {underlyingTokenSymbol} on {network} will run out in 1 week, [top-up here]()."

Link to my recurring donations tab

### When user runs out of stream balance 
> "Your Stream Balance in {tokenSymbol} on {network} has run out of funds, subsequently some of your recurring donations have ended. [Manage your Recurring Donations]()"

Link to my donations page

### When new recurring donation is created for their project 
> "Congratulations, your project {projectName} has a [new recurring donation]()."

 link to my project page
 
cc: @MoeNick

**Comment by divine-comedian** [comment]
@CarlosQ96 will add DB entity to notification center - need to make an issue for email journeys related to notifications @divine-comedian

**Comment by maryjaf** [comment]
> ## For Project Owner
> ### When new recurring donation is created for their project
> > "Congratulations, your project {projectName} has a new recurring donation."
> 
> link to my project page
> 
> cc: @MoeNick

when I create new recurring donation , my project owner does not receive a new notification 

https://staging.giveth.io/project/testupdate1000?tab=donations
<img width="1388" alt="image" src="https://github.com/Giveth/notification-center/assets/111529185/666084d1-8329-4491-8106-bdf5a3eec717">


project owner:
https://staging.giveth.io/user/0xcd192b61a8dd586a97592555c1f5709e032f2505
<img width="1283" alt="image" src="https://github.com/Giveth/notification-center/assets/111529185/6f057cd0-3aeb-4b07-9860-dee73937573c">

the last notification is related to a one time donation

**Comment by maryjaf** [comment]
I didn't receive any notification for recurring donation and I moved it to inprogress for more checking 
@CarlosQ96 @jainkrati

**Comment by MoeNick** [comment]
@RamRamez any updates?

**Comment by divine-comedian** [comment]
> > ### When user runs out of stream balance
> > > "Your Stream Balance in {tokenSymbol} on {network} has run out of funds, subsequently some of your recurring donations have ended. Manage your Recurring Donations"
> 
> * [ ]  1-
> 
> should a notification be sent when user manually ends the recurring donation? @CarlosQ96 @divine-comedian if yes I didn't receive notification for this

No - the user should not get any notification when they manually end a recurring donation.

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
I received 3 notification for " optimism-sepolia-testnet will run out in 1 month" it seems the reason is that I have 3 supprting project with this stream 
I thought in this situation I should receive one notification , am I right ? @RamRamez @divine-comedian 
<img width="1306" alt="image" src="https://github.com/Giveth/notification-center/assets/111529185/c361e079-ba99-4205-a50a-2a7162b0c523">

**Comment by divine-comedian** [comment]
Correct- You should receive just 1 notification since it is related to the stream balance - not the number of projects being supported by it

**Comment by maryjaf** [comment]
one question @MoeNick @divine-comedian 
There is no item for this new notifications in "notification setting"
https://staging.giveth.io/notifications/settings
Tt should be added like other notification or not important for this phase?

**Comment by divine-comedian** [comment]
> one question @MoeNick @divine-comedian There is no item for this new notifications in "notification setting" https://staging.giveth.io/notifications/settings Tt should be added like other notification or not important for this phase?

Nice catch! Yes they should have an entry in there, allowing the user to control if they receive emails & in-app notifs or not 

There should be just one new entry: 

## Supported project Activity -> 
### Stream Balance Warnings 
'Notify me when any of my Stream Balances are running low' 

---

For recurring donation received we can consider it a part of the existing settings entry for 'Donation received'

**Comment by maryjaf** [comment]
> ### When user runs out of stream balance
> > "Your Stream Balance in {tokenSymbol} on {network} has run out of funds, subsequently some of your recurring donations have ended. Manage your Recurring Donations"
> 
> Link to my donations page

- [ ] 3- My stream balance runs out but I haven't receive any notification after "1 week notification", 
please take a look @RamRamez 

![image](https://github.com/Giveth/notification-center/assets/111529185/51609059-c707-4f00-917e-7cf4acef892e)

**Comment by RamRamez** [comment]
> > ### When user runs out of stream balance
> > > "Your Stream Balance in {tokenSymbol} on {network} has run out of funds, subsequently some of your recurring donations have ended. Manage your Recurring Donations"
> > 
> > 
> > Link to my donations page
> 
> * [ ]  3- My stream balance runs out but I haven't receive any notification after " runs out after 1 week" notification,
>   please take a look @RamRamez
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/322739468-51609059-c707-4f00-917e-7cf4acef892e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzIzMjUsIm5iZiI6MTcxMzI3MjAyNSwicGF0aCI6Ii8xMTE1MjkxODUvMzIyNzM5NDY4LTUxNjA5MDU5LWM3MDctNGYwMC05MTdlLTdjZjRhY2VmODkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMjUzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDVkMjdlOTlmNDIyZDNkMzAxYzkxMjEwZGE3Y2YzZTUwMDliYTZjMjExNGQyMGFmYTExNDE1MWYzMWQ3MGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ET8AyAp4mKY6Rd-oDr67AtQn-X1Nxr_D37a15zJ5gaQ)

We fetch only active recurring donations, and when balance is depleted, the status will be ended. I can change it to fetch all recurring donations, but the problem is we don't know if user has stopped the recurring donation or the donation stream is just depleted. I trying to find a workaround.
@CarlosQ96 do you have any ideas how to figure this out?

**Comment by maryjaf** [comment]
> > ### When user runs out of stream balance
> > > "Your Stream Balance in {tokenSymbol} on {network} has run out of funds, subsequently some of your recurring donations have ended. Manage your Recurring Donations"
> > 
> > 
> > Link to my donations page
> 
> * [ ]  3- My stream balance runs out but I haven't receive any notification after " runs out after 1 week" notification,
>   please take a look @RamRamez
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/322739468-51609059-c707-4f00-917e-7cf4acef892e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Njc3ODAsIm5iZiI6MTcxMzQ2NzQ4MCwicGF0aCI6Ii8xMTE1MjkxODUvMzIyNzM5NDY4LTUxNjA5MDU5LWM3MDctNGYwMC05MTdlLTdjZjRhY2VmODkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxOTExMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmI0NGMyMzRkZGI0MGQ0YzYyNWJmMDQ5MWYzNWQ1OGVjMWExYzM3ZjAwNDI4OWUwYTIyYTFjY2FmOWExYTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3JcKo8Y_RN6lxYJa7xTufW8TaZkEeyXM7tfEI0mVOjI)

This problem also hasn’t been resolved yet
Let me know when these 2 problems be resolved

**Comment by RamRamez** [comment]
Notification and email for "When user runs out of stream balance" is done and ready to be tested on staging.

**Comment by RamRamez** [comment]
@maryjaf for testing, we stream is stopped via our UI, we don't send depleted notification, but when it'a stopped via SuperFluid UI, we send notif and email.

**Comment by maryjaf** [comment]
> > > one question @MoeNick @divine-comedian There is no item for this new notifications in "notification setting" https://staging.giveth.io/notifications/settings Tt should be added like other notification or not important for this phase?
> > 
> > 
> > Nice catch! Yes they should have an entry in there, allowing the user to control if they receive emails & in-app notifs or not
> > There should be just one new entry:
> > ## Supported project Activity ->
> > ### Stream Balance Warnings
> > 'Notify me when any of my Stream Balances are running low'
> > For recurring donation received we can consider it a part of the existing settings entry for 'Donation received'
> 
> This item hasn't been resolved yet @RamRamez @CarlosQ96 I'm not sure this should be fixed from backend or frontend side

And what a bout this problem? @RamRamez

**Comment by RamRamez** [comment]
> > > > one question @MoeNick @divine-comedian There is no item for this new notifications in "notification setting" https://staging.giveth.io/notifications/settings Tt should be added like other notification or not important for this phase?
> > > 
> > > 
> > > Nice catch! Yes they should have an entry in there, allowing the user to control if they receive emails & in-app notifs or not
> > > There should be just one new entry:
> > > ## Supported project Activity ->
> > > ### Stream Balance Warnings
> > > 'Notify me when any of my Stream Balances are running low'
> > > For recurring donation received we can consider it a part of the existing settings entry for 'Donation received'
> > 
> > 
> > This item hasn't been resolved yet @RamRamez @CarlosQ96 I'm not sure this should be fixed from backend or frontend side
> 
> And what a bout this problem? @RamRamez

I checked and we have three notifications in DB for Superfluid but we should show only one in FE. I'm not sure how can we  handle this. @CarlosQ96 can you take a look?

**Comment by divine-comedian** [comment]
To clarify here for you both @RamRamez @CarlosQ96  

The three "balance warning notificiations", 1 month warning, 1 week warning & ended should be toggled on/off with one entry on the FE

The recurring donation received should be toggled on/off by this same existing entry: 

![image](https://github.com/Giveth/notification-center/assets/67759413/5092e17a-9657-434d-8575-1e1187f3ccd5)

**Comment by maryjaf** [comment]
I haven't seen any changed in notification setting page @RamRamez 
![image](https://github.com/Giveth/notification-center/assets/111529185/cf909255-fd96-41c0-bfb8-001c3a6af7e4)

**Comment by RamRamez** [comment]
@maryjaf it's placed in the supported project activity as it was requested by Mitch in this issue
<img width="1260" alt="image" src="https://github.com/Giveth/notification-center/assets/73441857/f16749ac-790b-4757-a8f5-27cacba51d11">

**Comment by maryjaf** [comment]
Thanks @RamRamez This issue has been resolved
